version: '3.9'

services:
  # MongoDB Services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node API Service
  api:
    build: .
    ports:
      - 5200:5200
    environment: 
      PORT: 5200
      CONNECTION_STRING: mongodb://mongo_db/27017
      DATABASE: person-api
      NAME: person-api
    depends_on:
      - mongo_db

volumes: 
  mongo_db: {}
